### ISSUE TITLE
Wrong merging of yaml inputs with the same plugin name 

### ISSUE THREAD

**Issue by czervenyvlk** [dsc-team/puppet-telegraf#1]
Hi,
I'm trying to configure [win_perf_counters](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/win_perf_counters) inputs in Hiera yaml but generated telegraf.conf only contain last input entry and ignore the other one.

How to reproduce:

**hiera.yaml**
```
telegraf::inputs:
  win_perf_counters.object:
    ObjectName: "Processor"
    Instances:
      - "*"
    Counters:
      - "% Idle Time"
      - "% Interrupt Time"
      - "% Privileged Time"
      - "% User Time"
      - "% Processor Time"
    Measurement: "win_cpu"

  win_perf_counters.object:
    ObjectName: "Network Interface"
    Instances:
      - "*"
    Counters:
      - "Bytes Received/sec"
      - "Bytes Sent/sec"
      - "Packets Received/sec"
      - "Packets Sent/sec"
    Measurement: "win_net"
```
**generated telegraf.conf**
```
[[inputs.win_perf_counters.object]]
  ObjectName = "Network Interface"
  Instances = ["*"]
  Counters = ["Bytes Received/sec", "Bytes Sent/sec", "Packets Received/sec", "Packets Sent/sec"]
  Measurement = "win_net"
```
